### ISSUE TITLE
Error in (function (cl, name, valueClass)

### ISSUE THREAD

**Issue by mahmood225** [christpa/DMRScan#11]
Hi,
I have used the makeCpGregions() function to generate a list of clusters, but I faced with flowing error:
"Error in (function (cl, name, valueClass)  : 
  assignment of an object of class “list” is not valid for @‘regions’ in an object of class “RegionList”; is(value, "array") is not TRUE"
I used R version 3.4.1 (2017-06-30) and DMRScan version 1.0.0.
Could you please tell me how can I fix this?
The best,
Mahmoud

**Comment by christpa** [comment]
Dear Mahmoud,

Could you try to update to DMRScan v 1.4.6 to see if this solves the issue?

**Comment by mahmood225** [comment]
Dear Christpa,
I used updated DMRScan (v 1.4.6), but the error is still there!

**Comment by christpa** [comment]
Strange. 
How is your input for makeCpGrions() structured? It should be three 1d vectors with; Z-scores (or eqvivalent) which is numeric, one with the positions (integer) and one with the chromosome (integer). 

Have you tried to run the example described in ?makeCpGregions to see if that runs? 

Best
Christian

**Comment by christpa** [comment]
Dear Mahmoud,

In the development version of DMRScan (v 1.5.3), the makeCpGregions() got a complete overhal to make it compatible with GenomicRanges, so this should probably have fixed the issue.

**Comment by mahmood225** [comment]
Dear Christian:
Thank you so much for your update. I will try this version to solve the problem. I hope the issue be fixed.

Best,

Mahmoud
